### ISSUE TITLE
Cannot build css

### ISSUE THREAD

**Issue by gitim** [floatdrop/gulp-bem#12]
Hi! Wanted to use gulp-bem for building css in my bem project, but it falls with an error. Can you help me to solve this problem? Here the error and the stack trace:
```
gitim-osx2:project gitim$ gulp css
[13:22:19] Using gulpfile ~/Work/project/gulpfile.js
[13:22:19] Starting 'css'...
/Users/gitim/Work/project/node_modules/gulp-bem/src.js:10
    var result = join(dep.level, dep.block);
                         ^
TypeError: Cannot read property 'level' of undefined
    at Function.path (/Users/gitim/Work/project/node_modules/gulp-bem/src.js:10:26)
    at /Users/gitim/Work/project/node_modules/gulp-bem/src.js:28:34
    at Array.map (native)
    at DestroyableTransform.findFile [as _transform] (/Users/gitim/Work/project/node_modules/gulp-bem/src.js:27:14)
    at DestroyableTransform.Transform._read (/Users/gitim/Work/project/node_modules/gulp-bem/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/gitim/Work/project/node_modules/gulp-bem/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/gitim/Work/project/node_modules/gulp-bem/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at clearBuffer (/Users/gitim/Work/project/node_modules/gulp-bem/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:385:7)
    at onwrite (/Users/gitim/Work/project/node_modules/gulp-bem/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:322:7)
    at WritableState.onwrite (/Users/gitim/Work/project/node_modules/gulp-bem/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:115:5)
```
the structure of my project:
![2015-04-12 13 27 03](https://cloud.githubusercontent.com/assets/3778452/7105238/aa07a394-e117-11e4-99c0-b0e0a3685d98.png)
and gulp task, that I use:
```
var levels = [
    'blocks',
    'bundles/index/blocks'
];
var deps = bem(levels);
gulp.task('css', function () {
    deps.deps('bundles/index/blocks/page')
        .pipe(bem.src('{bem}.css'))
        .pipe(concat('index.css'))
        .pipe(gulp.dest('./dist'));
});
```

**Comment by matmuchrapna** [comment]
Hi, thanks for feedback. Can you provide whole project for debugging (if it’s possible)? It will be much easier to solve the issue

**Comment by gitim** [comment]
Thanks for quick response! Yes, sure. Because I am still experimenting with my project I pushed [here](https://github.com/gitim/Project) only the part related to gulp.

**Comment by floatdrop** [comment]
Hm... https://github.com/gitim/Project is working for me. `css` task builds `index.css` fine.

**Comment by matmuchrapna** [comment]
I reproduced the error, will investigate soon

**Comment by matmuchrapna** [comment]
FAIL nodejs v0.12.2

    ➜  Project git:(master) ✗ n latest && node -v
    v0.12.2
    ➜  Project git:(master) ✗ gulp css
    [11:48:35] Using gulpfile ~/projects/Project/gulpfile.js
    [11:48:35] Starting 'css'...
    [11:48:36] Finished 'css' after 111 ms
    /Users/vladimir/projects/Project/node_modules/gulp-bem/src.js:10
        var result = join(dep.level, dep.block);
                             ^
    TypeError: Cannot read property 'level' of undefined

FAIL iojs v1.7.1

    ➜  Project git:(master) ✗ n io latest && node -v
    v1.7.1
    ➜  Project git:(master) ✗ gulp css
    [11:51:28] Using gulpfile ~/projects/Project/gulpfile.js
    [11:51:28] Starting 'css'...
    [11:51:28] Finished 'css' after 108 ms
    /Users/vladimir/projects/Project/node_modules/gulp-bem/src.js:10
        var result = join(dep.level, dep.block);
                             ^
    TypeError: Cannot read property 'level' of undefined

SUCCESS nodejs v0.10.38

    ➜  Project git:(master) ✗ node -v
    v0.10.38
    ➜  Project git:(master) ✗ gulp css
    [11:52:34] Using gulpfile ~/projects/Project/gulpfile.js
    [11:52:34] Starting 'css'...
    [11:52:34] Finished 'css' after 51 ms

**Comment by matmuchrapna** [comment]
Add pr #13 with tests for iojs and latest nodejs

**Comment by matmuchrapna** [comment]
but tests seems to be passed, so it’s another problem

**Comment by matmuchrapna** [comment]
➜  Project git:(master) ✗ gulp css
    [12:11:29] Using gulpfile ~/projects/Project/gulpfile.js
    [12:11:29] Starting 'css'...
    [12:11:29] Finished 'css' after 105 ms
    /Users/vladimir/projects/Project/node_modules/gulp-bem/src.js:10
        var result = join(dep.level, dep.block);

    ➜  Project git:(master) ✗ cd node_modules/gulp-bem
    ➜  gulp-bem git:(master) ✗ npm i
    ➜  gulp-bem git:(master) ✗ npm test

    > gulp-bem@1.0.1 test /Users/vladimir/projects/Project/node_modules/gulp-bem
    > mocha -R spec

    /Users/vladimir/projects/Project/node_modules/gulp-bem/node_modules/mocha/lib/utils.js:577
          if (!files.length) throw new Error("cannot resolve path (or pattern) '"
                                   ^
    Error: cannot resolve path (or pattern) 'test'
        at Object.lookupFiles (/Users/vladimir/projects/Project/node_modules/gulp-bem/node_modules/mocha/lib/utils.js:577:32)
        at /Users/vladimir/projects/Project/node_modules/gulp-bem/node_modules/mocha/bin/_mocha:320:30
        at Array.forEach (native)
        at Object.<anonymous> (/Users/vladimir/projects/Project/node_modules/gulp-bem/node_modules/mocha/bin/_mocha:319:6)
        at Module._compile (module.js:410:26)
        at Object.Module._extensions..js (module.js:428:10)
        at Module.load (module.js:335:32)
        at Function.Module._load (module.js:290:12)
        at Function.Module.runMain (module.js:451:10)
        at startup (node.js:124:18)
        at node.js:868:3
    npm ERR! Test failed.  See above for more details.

**Comment by matmuchrapna** [comment]
Strange that tests not failing

**Comment by matmuchrapna** [comment]
There was an issue with deprecated `customFds` and non-stable `stream-array` used bem-deps. But now seems to be fixed. I have test it on latest nodejs and iojs releases and on 0.10 one.

**Comment by gitim** [comment]
Tried with new updates, now it works! Thank you!
